version: "2"

linters:
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: error-return
        - name: error-strings
        - name: increment-decrement
        - name: indent-error-flow
        - name: range

formatters:
  enable:
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0